-- ==============================================================================
-- Modes Power Services CMS — Initial Seed Data
-- ==============================================================================

-- 1. Seed Site Settings (Singleton)
INSERT INTO public.site_settings (id, hero_image_url, about_image_url, cta_image_url, og_image_url)
VALUES ('default', NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- 2. Seed Gallery Items
INSERT INTO public.gallery_items (title, category, image_path, alt_text, sort_order, published)
VALUES
    ('33kV Primary Substation Transformer Installation', 'installations', NULL, '33kV Primary Substation Transformer Installation in Tema', 1, true),
    ('FLIR Thermal Imaging & Thermographic Scan', 'maintenance', NULL, 'FLIR Thermal Analysis on 1600A Busbar Joint', 2, true),
    ('Power Quality Harmonic Analyzer Deployment', 'audits', NULL, 'IEC Class A 7-Day Power Logging in Spintex', 3, true),
    ('750kWp Commercial Solar PV Array Installation', 'solar_custom', NULL, '750 kWp Commercial Solar Array in Airport Residential', 4, true),
    ('Custom Motor Control Center (MCC) Panel Fabrication', 'installations', NULL, 'Form 4B MCC Panel Assembly in Accra Workshop', 5, true),
    ('Emergency HV Underground Cable Jointing & TDR Testing', 'maintenance', NULL, '11kV Cable Jointing and TDR Testing in Ridge', 6, true),
    ('Automated Power Factor Correction (PFC) Capacitor Bank', 'audits', NULL, '400 kVAR Detuned Capacitor Banks in Kumasi', 7, true),
    ('Lithium BESS Energy Storage & Inverter Room', 'solar_custom', NULL, '1.2 MWh LiFePO4 BESS Storage Room in Data Center', 8, true);

-- 3. Seed Projects
INSERT INTO public.projects (client_name, title, category, description, outcome, cover_image_path, sort_order, published)
VALUES
    ('Tema Heavy Steel Mills & Processing Ltd.', '33kV/11kV Heavy Industrial Substation Overhaul', 'Industrial', 'Complete replacement of aged oil circuit breakers with ABB vacuum switchgear, installation of dual 1,750kVA step-down transformers, and underground 33kV XLPE cable reticulation.', 'Eliminated monthly unplanned grid trip-outs, reduced voltage sag by 94%, and enhanced plant power factor from 0.74 to 0.99 with automated capacitor banks.', NULL, 1, true),
    ('Airport City Commercial Towers', '750kWp Rooftop Solar PV & 1.2MWh BESS Microgrid', 'Solar & Hybrid', 'Turnkey engineering, procurement, and construction (EPC) of a hybrid solar-plus-storage microgrid synchronized with utility grid and triple 800kVA backup diesel generators.', 'Offset 48% of daytime grid electricity consumption, cut diesel fuel consumption by 62,000 liters annually, and guaranteed sub-10ms seamless transfer during utility dropouts.', NULL, 2, true),
    ('Ashanti Regional Precious Metals Processing', 'Comprehensive Power Quality Audit & Harmonic Filtering', 'Infrastructure', 'High-resolution Class-A power quality logging over 14 days, isolation of harmonic distortion generated by heavy non-linear induction furnaces, and installation of active harmonic filters.', 'Reduced Total Harmonic Voltage Distortion (THDv) from 11.4% to 2.1% (well within IEEE 519 limits), eliminating recurrent VFD drive burnouts and saving $45,000/yr in equipment replacement.', NULL, 3, true),
    ('Greater Accra Specialized Surgical & Diagnostics Center', 'Critical Medical Center 11kV Power Distribution & Dual Redundancy', 'Commercial', 'Turnkey electrical fitout for surgical suites, ICU backup distribution, automatic generator synchronization board, isolated power systems (IPS) for operating theaters, and medical-grade earthing.', 'Zero interruption during grid fluctuations; passed Ministry of Health and Energy Commission hospital electrical safety compliance with 100% score.', NULL, 4, true),
    ('Western Port Logistics & Cold Chain Hub', 'Port Cold Storage & Container Yard High-Mast Electrification', 'Industrial', 'Underground medium-voltage duct bank construction, 12 high-mast LED floodlight towers with lightning protection, reefer plug distribution boards for 160 refrigerated containers.', 'Enabled continuous 24/7 ship loading/unloading operations with automated reefer power monitoring and surge protection.', NULL, 5, true),
    ('Cantonments Luxury Residences Consortium', 'Smart Automation & Solar Microgrid for 24-Unit Luxury Estate', 'Solar & Hybrid', 'Underground residential cabling, individual smart sub-metering, centralized 320kWp solar carport installation, and integrated KNX home automation backbone.', 'Reduced tenant utility fees by 40% with zero noise pollution during daytime grid outages.', NULL, 6, true);

-- 4. Seed Team Members
INSERT INTO public.team_members (name, role, tagline, bio_bullets, photo_path, linkedin_url, sort_order, published)
VALUES
    ('Ing. Emmanuel Modes Mensah', 'Managing Director & Lead Power Systems Engineer', '“True engineering excellence lies in building power systems that operate with zero compromise on safety and longevity.”', ARRAY['BSc & MSc Electrical & Electronic Engineering (KNUST)', 'Fellow, Ghana Institution of Engineering (GhIE)', 'Energy Commission Certified Lead Electrical Inspector', 'Over 20 years leading high-voltage substation and industrial grid projects'], NULL, 'https://linkedin.com/in/modes-power-lead', 1, true),
    ('Ing. Kwabena Osei-Tutu', 'Head of Industrial Projects & Substation Engineering', '“Precision in substation protection and switchgear timing is what prevents single-point failure across industrial plants.”', ARRAY['BSc Electrical Engineering (University of Mines & Technology, Tarkwa)', 'Professional Member, GhIE & IEEE Power & Energy Society', 'Specialist in 33kV/11kV Protection Relay Coordination and Vacuum Switchgear', '14+ years in heavy industrial and mining electrification'], NULL, 'https://linkedin.com/in/modes-substation-head', 2, true),
    ('Abena Serwaa Boateng', 'Director of Renewable Energy & Microgrids', '“Integrating solar PV and battery storage isn’t just green — it is the single best hedge against industrial power costs in Africa.”', ARRAY['BSc Mechanical & Energy Engineering, MSc Renewable Power Systems', 'Certified Energy Manager (CEM®) & NABCEP PV Installation Professional', 'Pioneered 15+ commercial solar microgrid projects across West Africa', 'Expert in closed-transition ATS and BESS battery chemistry management'], NULL, 'https://linkedin.com/in/modes-renewables-lead', 3, true),
    ('Ing. Michael Kofi Addo', 'Director of Safety, Quality Assurance & 24/7 Operations', '“In high-voltage engineering, safety isn’t a checklist — it is our culture, our duty, and our core promise to every client.”', ARRAY['BSc Electrical Engineering (KNUST), NEBOSH International Diploma in HSE', 'Lead Auditor ISO 45001 (Occupational Health & Safety) & ISO 9001', 'Commander of Modes 24/7 Rapid Emergency Response Unit', '12+ years zero-loss-time safety management in high-voltage environments'], NULL, 'https://linkedin.com/in/modes-safety-ops', 4, true);
