import { ProjectCaseStudy } from '@/types';

export const PROJECTS_DATA: ProjectCaseStudy[] = [
  {
    id: 'tema-industrial-substation',
    title: '33kV/11kV Heavy Industrial Substation Overhaul',
    category: 'Industrial',
    client: 'Tema Heavy Steel Mills & Processing Ltd.',
    location: 'Tema Heavy Industrial Area, Greater Accra',
    capacity: '3.5 MVA Grid Connection',
    scope:
      'Complete replacement of aged oil circuit breakers with ABB vacuum switchgear, installation of dual 1,750kVA step-down transformers, and underground 33kV XLPE cable reticulation.',
    timeline: '5 Months (Completed Zero-Lost-Time-Incidents)',
    outcome:
      'Eliminated monthly unplanned grid trip-outs, reduced voltage sag by 94%, and enhanced plant power factor from 0.74 to 0.99 with automated capacitor banks.',
    image: null,
    highlight: '99.99% Uptime Achieved Across 24/7 Production Shifts',
    tags: ['33kV Substation', 'Vacuum Switchgear', 'Power Factor Correction', 'IEEE Compliance'],
  },
  {
    id: 'accra-financial-center-hybrid',
    title: '750kWp Rooftop Solar PV & 1.2MWh BESS Microgrid',
    category: 'Solar & Hybrid',
    client: 'Airport City Commercial Towers',
    location: 'Airport Residential / City Area, Accra',
    capacity: '750 kWp Solar + 1,200 kWh LiFePO4 BESS',
    scope:
      'Turnkey engineering, procurement, and construction (EPC) of a hybrid solar-plus-storage microgrid synchronized with utility grid and triple 800kVA backup diesel generators.',
    timeline: '4 Months',
    outcome:
      'Offset 48% of daytime grid electricity consumption, cut diesel fuel consumption by 62,000 liters annually, and guaranteed sub-10ms seamless transfer during utility dropouts.',
    image: null,
    highlight: '48% Grid Electricity Cost Reduction',
    tags: ['Solar Microgrid', 'BESS Energy Storage', 'Closed-Transition ATS', 'SCADA Monitoring'],
  },
  {
    id: 'ashanti-gold-refinery-audit',
    title: 'Comprehensive Power Quality Audit & Harmonic Filtering',
    category: 'Infrastructure',
    client: 'Ashanti Regional Precious Metals Processing',
    location: 'Obuasi / Kumasi Corridor, Ashanti Region',
    capacity: '4.2 MW Connected Load',
    scope:
      'High-resolution Class-A power quality logging over 14 days, isolation of harmonic distortion generated by heavy non-linear induction furnaces, and installation of active harmonic filters.',
    timeline: '6 Weeks',
    outcome:
      'Reduced Total Harmonic Voltage Distortion (THDv) from 11.4% to 2.1% (well within IEEE 519 limits), eliminating recurrent VFD drive burnouts and saving $45,000/yr in equipment replacement.',
    image: null,
    highlight: 'Harmonic Distortion Slashed by 81.5%',
    tags: ['Power Quality Audit', 'Active Harmonic Filters', 'Thermography', 'IEEE 519'],
  },
  {
    id: 'ridge-hospital-emergency-power',
    title: 'Critical Medical Center 11kV Power Distribution & Dual Redundancy',
    category: 'Commercial',
    client: 'Greater Accra Specialized Surgical & Diagnostics Center',
    location: 'Ridge / Central Accra',
    capacity: '1,500 kVA Dual-Feed Substation',
    scope:
      'Turnkey electrical fitout for surgical suites, ICU backup distribution, automatic generator synchronization board, isolated power systems (IPS) for operating theaters, and medical-grade earthing.',
    timeline: '7 Months',
    outcome:
      'Zero interruption during grid fluctuations; passed Ministry of Health and Energy Commission hospital electrical safety compliance with 100% score.',
    image: null,
    highlight: 'Tier-4 Reliability for Critical Healthcare',
    tags: ['Healthcare Power', 'Isolated Power Systems', 'Medical Earthing', 'Dual Redundancy'],
  },
  {
    id: 'takoradi-harbor-logistics-electrification',
    title: 'Port Cold Storage & Container Yard High-Mast Electrification',
    category: 'Industrial',
    client: 'Western Port Logistics & Cold Chain Hub',
    location: 'Takoradi Port Industrial Enclave, Western Region',
    capacity: '2.0 MVA Reticulation',
    scope:
      'Underground medium-voltage duct bank construction, 12 high-mast LED floodlight towers with lightning protection, reefer plug distribution boards for 160 refrigerated containers.',
    timeline: '5 Months',
    outcome:
      'Enabled continuous 24/7 ship loading/unloading operations with automated reefer power monitoring and surge protection.',
    image: null,
    highlight: '160 Simultaneous Reefer Plugs Energized',
    tags: ['Port Electrification', 'High-Mast Lighting', 'Medium Voltage', 'Industrial Cable Ducting'],
  },
  {
    id: 'cantonments-luxury-residential-estate',
    title: 'Smart Automation & Solar Microgrid for 24-Unit Luxury Estate',
    category: 'Solar & Hybrid',
    client: 'Cantonments Luxury Residences Consortium',
    location: 'Cantonments, Accra',
    capacity: '320 kWp Solar + 400 kVA Generator Sync',
    scope:
      'Underground residential cabling, individual smart sub-metering, centralized 320kWp solar carport installation, and integrated KNX home automation backbone.',
    timeline: '6 Months',
    outcome:
      'Reduced tenant utility fees by 40% with zero noise pollution during daytime grid outages.',
    image: null,
    highlight: 'Zero-Noise Daylight Grid Independence',
    tags: ['Smart Automation', 'Solar Carport', 'Smart Submetering', 'Residential Microgrid'],
  },
];

export const PROJECTS = PROJECTS_DATA.map((p) => ({
  id: p.id,
  title: p.title,
  client: p.client,
  category: p.category,
  description: p.scope,
  outcome: p.outcome,
  image: p.image,
  published: true,
}));
